// Code generated by @open-rpc/generator DO NOT EDIT.
import _ from 'lodash'

import { RequestArgs, RequestPayload } from '@canton-network/core-types'
import { RpcTransport } from '@canton-network/core-rpc-transport'

/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 *
 * The unique identifier of the command associated with the transaction.
 *
 */
export type CommandId = string
type AlwaysTrue = any
/**
 *
 * Inner shape is defined by the Canton Ledger API CreateCommand schema; do not re-specify here.
 *
 */
export interface CreateCommandPayload {
    [key: string]: any
}
export interface CreateCommand {
    CreateCommand: CreateCommandPayload
}
/**
 *
 * Inner shape is defined by the Canton Ledger API ExerciseCommand schema; do not re-specify here.
 *
 */
export interface ExerciseCommandPayload {
    [key: string]: any
}
export interface ExerciseCommand {
    ExerciseCommand: ExerciseCommandPayload
}
/**
 *
 * Inner shape is defined by the Canton Ledger API CreateAndExerciseCommand schema; do not re-specify here.
 *
 */
export interface CreateAndExerciseCommandPayload {
    [key: string]: any
}
export interface CreateAndExerciseCommand {
    CreateAndExerciseCommand: CreateAndExerciseCommandPayload
}
/**
 *
 * Inner shape is defined by the Canton Ledger API ExerciseByKeyCommand schema; do not re-specify here.
 *
 */
export interface ExerciseByKeyCommandPayload {
    [key: string]: any
}
export interface ExerciseByKeyCommand {
    ExerciseByKeyCommand: ExerciseByKeyCommandPayload
}
/**
 *
 * A Daml command atom. Mirror of the Canton Ledger API Command union; inner shapes are intentionally opaque so the dApp layer never drifts from the Ledger API contract.
 *
 */
export type Command =
    | CreateCommand
    | ExerciseCommand
    | CreateAndExerciseCommand
    | ExerciseByKeyCommand
/**
 *
 * Non-empty array of Daml command atoms to submit atomically as a single transaction.
 *
 */
export type Commands = Command[]
/**
 *
 * The party that signed the transaction.
 *
 */
export type Party = string
/**
 *
 * Set of parties on whose behalf the command should be executed, if submitted. If not set, the primary wallet's party is used.
 *
 */
export type ActAs = Party[]
/**
 *
 * Set of parties that should be granted read access to the command, if submitted. If not set, no additional read parties are granted.
 *
 */
export type ReadAs = Party[]
/**
 *
 * The template identifier of the disclosed contract.
 *
 */
export type TemplateId = string
/**
 *
 * The unique identifier of the disclosed contract.
 *
 */
export type ContractId = string
/**
 *
 * The blob data of the created event for the disclosed contract.
 *
 */
export type CreatedEventBlob = string
/**
 *
 * If not set, a suitable synchronizer that this node is connected to will be chosen.
 *
 */
export type SynchronizerId = string
/**
 *
 * Structure representing a disclosed contract for transaction execution
 *
 */
export interface DisclosedContract {
    templateId?: TemplateId
    contractId?: ContractId
    createdEventBlob: CreatedEventBlob
    synchronizerId?: SynchronizerId
}
/**
 *
 * List of contract IDs to be disclosed with the command.
 *
 */
export type DisclosedContracts = DisclosedContract[]
export type PackageId = string
/**
 *
 * The package-id selection preference of the client for resolving package names and interface instances in command submission and interpretation
 *
 */
export type PackageIdSelectionPreference = PackageId[]
/**
 *
 * The message to sign.
 *
 */
export type Message = string
export type TopologyTransactionBase64 = string
/**
 *
 * Base64-encoded, UntypedVersionedMessage-wrapped topology transactions to sign as one bundle.
 *
 */
export type Transactions = TopologyTransactionBase64[]
/**
 *
 * Base64-encoded prepared transaction bytes to submit, as returned by the ledger API's interactive-submission prepare endpoint.
 *
 */
export type PreparedTransaction = string
/**
 *
 * As supplied by the caller; the wallet independently recomputes this from preparedTransaction and refuses to submit if it doesn't match, since a mismatch here would mean submitting a different transaction than the one every owner actually signed.
 *
 */
export type PreparedTransactionHash = string
/**
 *
 * The party ID corresponding to the wallet.
 *
 */
export type PartyId = string
/**
 *
 * The signature over the prepared transaction's hash.
 *
 */
export type Signature = string
/**
 *
 * The public key that produced the signature.
 *
 */
export type SignedBy = string
/**
 *
 * One owner's signature over a prepared transaction, collected off-ledger before combined submission.
 *
 */
export interface SignatureEntry {
    signature: Signature
    signedBy: SignedBy
}
/**
 *
 * Every owner's collected signature over preparedTransactionHash, including the finalizer's own.
 *
 */
export type Signatures = SignatureEntry[]
export type RequestMethod = 'get' | 'post' | 'patch' | 'put' | 'delete'
export type Resource = string
export interface Body {
    [key: string]: any
}
/**
 *
 * Query parameters as key-value pairs.
 *
 */
export interface Query {
    [key: string]: any
}
/**
 *
 * Path parameters as key-value pairs.
 *
 */
export interface Path {
    [key: string]: any
}
/**
 *
 * The unique identifier of the Provider.
 *
 */
export type ProviderId = string
/**
 *
 * The version of the Provider.
 *
 */
export type Version = string
/**
 *
 * The type of client that implements the Provider.
 *
 */
export type ProviderType = 'browser' | 'desktop' | 'mobile' | 'remote'
/**
 *
 * The URL of the Wallet Provider.
 *
 */
export type Url = string
/**
 *
 * A URL that points to a user interface.
 *
 */
export type UserUrl = string
/**
 *
 * Represents a Provider.
 *
 */
export interface Provider {
    id: ProviderId
    version?: Version
    providerType?: ProviderType
    url?: Url
    userUrl?: UserUrl
}
/**
 *
 * Whether or not the user is authenticated with the Wallet.
 *
 */
export type IsConnectedValue = boolean
/**
 *
 * Reason for the wallet state, e.g., 'no signing provider matched'.
 *
 */
export type Reason = string
/**
 *
 * Whether or not a connection to a network is established.
 *
 */
export type IsNetworkConnected = boolean
/**
 *
 * If not connected to a network, the reason why.
 *
 */
export type NetworkReason = string
export interface ConnectResult {
    isConnected: IsConnectedValue
    reason?: Reason
    isNetworkConnected: IsNetworkConnected
    networkReason?: NetworkReason
    userUrl?: UserUrl
}
/**
 *
 * The network ID the wallet corresponds to.
 *
 */
export type NetworkId = string
/**
 *
 * The base URL of the ledger API.
 *
 */
export type LedgerApiUrl = string
/**
 *
 * JWT authentication token.
 *
 */
export type AccessToken = string
/**
 *
 * Network information, if connected to a network.
 *
 */
export interface Network {
    networkId: NetworkId
    ledgerApi?: LedgerApiUrl
    accessToken?: AccessToken
}
/**
 *
 * The user identifier.
 *
 */
export type UserId = string
/**
 *
 * Session information, if authenticated.
 *
 */
export interface Session {
    accessToken: AccessToken
    userId: UserId
}
/**
 *
 * The unique identifier of the message associated with the message to be signed.
 *
 */
export type MessageId = string
/**
 *
 * The unique identifier of the signTopologyTransactions request associated with the bundle to be signed.
 *
 */
export type TopologyRequestId = string
/**
 *
 * The unique identifier of the signPreparedTransaction request associated with the transaction to be signed.
 *
 */
export type PreparedTransactionRequestId = string
/**
 *
 * Set as primary wallet for dApp usage.
 *
 */
export type Primary = boolean
/**
 *
 * The status of the wallet.
 *
 */
export type WalletStatus = 'initialized' | 'allocated' | 'removed'
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type Hint = string
/**
 *
 * The public key of the party.
 *
 */
export type PublicKey = string
/**
 *
 * The namespace of the party.
 *
 */
export type Namespace = string
/**
 *
 * The signing provider ID the wallet corresponds to.
 *
 */
export type SigningProviderId = string
/**
 *
 * Unique identifier of the signed transaction given by the Signing Provider. This may not be the same as the internal txId given by the Wallet Gateway.
 *
 */
export type ExternalTxId = string
/**
 *
 * The topology transactions
 *
 */
export type TopologyTransactions = string
/**
 *
 * Whether the wallet is disabled. Wallets are disabled when no signing provider matches the party's namespace during sync. Disabled wallets use participant as the default signing provider.
 *
 */
export type Disabled = boolean
/**
 *
 * Structure representing a wallet
 *
 */
export interface Wallet {
    primary: Primary
    partyId: PartyId
    status: WalletStatus
    hint: Hint
    publicKey: PublicKey
    namespace: Namespace
    networkId: NetworkId
    signingProviderId: SigningProviderId
    externalTxId?: ExternalTxId
    topologyTransactions?: TopologyTransactions
    disabled?: Disabled
    reason?: Reason
    safeAppUrl?: SafeAppUrl
    rights: Rights
}
/**
 *
 * A non-null value marks this wallet as a Gnosis-Safe-like decentralized party coordinated by the companion app at this URL. prepareExecute/execute for this party redirects here instead of the normal approve flow.
 *
 */
export type SafeAppUrl = string
export type PartyLevelRight = any
/**
 *
 * The rights of the wallet.
 *
 */
export type Rights = PartyLevelRight[]
/**
 *
 * The status of the prepared-transaction signature.
 *
 */
export type StatusPending = 'pending'
/**
 *
 * Event emitted when a transaction is pending.
 *
 */
export interface TxChangedPendingEvent {
    status: StatusPending
    commandId: CommandId
}
/**
 *
 * The status of the prepared-transaction signature.
 *
 */
export type StatusSigned = 'signed'
/**
 *
 * Payload for the TxChangedSignedEvent.
 *
 */
export interface TxChangedSignedPayload {
    signature: Signature
    signedBy: SignedBy
    party: Party
}
/**
 *
 * Event emitted when a transaction has been signed.
 *
 */
export interface TxChangedSignedEvent {
    status: StatusSigned
    commandId: CommandId
    payload: TxChangedSignedPayload
}
/**
 *
 * The status of the transaction.
 *
 */
export type StatusExecuted = 'executed'
/**
 *
 * The update ID corresponding to the transaction.
 *
 */
export type UpdateId = string
export type CompletionOffset = number
/**
 *
 * Payload for the TxChangedExecutedEvent.
 *
 */
export interface TxChangedExecutedPayload {
    updateId: UpdateId
    completionOffset: CompletionOffset
}
/**
 *
 * Event emitted when a transaction is executed against the participant.
 *
 */
export interface TxChangedExecutedEvent {
    status: StatusExecuted
    commandId: CommandId
    payload: TxChangedExecutedPayload
}
/**
 *
 * The status of the prepared-transaction signature.
 *
 */
export type StatusFailed = 'failed'
/**
 *
 * Event emitted when a transaction has failed.
 *
 */
export interface TxChangedFailedEvent {
    status: StatusFailed
    commandId: CommandId
}
/**
 *
 * Event emitted when a message signature is requested.
 *
 */
export interface MessageSignaturePendingEvent {
    status: StatusPending
    messageId: MessageId
}
/**
 *
 * Event emitted when a message signature is completed.
 *
 */
export interface MessageSignatureSignedEvent {
    status: StatusSigned
    messageId: MessageId
    signature: Signature
}
/**
 *
 * Event emitted when a message signature has failed.
 *
 */
export interface MessageSignatureFailedEvent {
    status: StatusFailed
    messageId: MessageId
}
/**
 *
 * Event emitted when a topology-transactions bundle signature is requested.
 *
 */
export interface TopologyTransactionsSignaturePendingEvent {
    status: StatusPending
    requestId: TopologyRequestId
}
/**
 *
 * The wallet-computed multiHash the signature is over, recomputed fresh from the stored raw transaction bytes at sign time -- never a cached or dApp-supplied value. Included so the dApp can cross-check it against its own computation.
 *
 */
export type MultiHash = string
/**
 *
 * Event emitted when a topology-transactions bundle signature is completed.
 *
 */
export interface TopologyTransactionsSignatureSignedEvent {
    status: StatusSigned
    requestId: TopologyRequestId
    signature: Signature
    multiHash: MultiHash
}
/**
 *
 * Event emitted when a topology-transactions bundle signature has failed.
 *
 */
export interface TopologyTransactionsSignatureFailedEvent {
    status: StatusFailed
    requestId: TopologyRequestId
}
/**
 *
 * Event emitted when a signPreparedTransaction signature is requested.
 *
 */
export interface PreparedTransactionSignaturePendingEvent {
    status: StatusPending
    requestId: PreparedTransactionRequestId
}
/**
 *
 * Event emitted when a signPreparedTransaction signature is completed.
 *
 */
export interface PreparedTransactionSignatureSignedEvent {
    status: StatusSigned
    requestId: PreparedTransactionRequestId
    signature: Signature
    signedBy: SignedBy
}
/**
 *
 * Event emitted when a signPreparedTransaction signature has failed.
 *
 */
export interface PreparedTransactionSignatureFailedEvent {
    status: StatusFailed
    requestId: PreparedTransactionRequestId
}
/**
 *
 * Structure representing the request for prepare and execute calls
 *
 */
export interface PrepareExecuteParams {
    commandId?: CommandId
    commands: Commands
    actAs?: ActAs
    readAs?: ReadAs
    disclosedContracts?: DisclosedContracts
    synchronizerId?: SynchronizerId
    packageIdSelectionPreference?: PackageIdSelectionPreference
}
/**
 *
 * Request to sign a message.
 *
 */
export interface SignMessageParams {
    message: Message
}
/**
 *
 * Request to sign a bundle of topology transactions with a single combined signature.
 *
 */
export interface SignTopologyTransactionsParams {
    transactions: Transactions
    synchronizerId?: SynchronizerId
}
/**
 *
 * Request to sign an already-prepared ordinary ledger transaction with the caller's own key.
 *
 */
export interface SignPreparedTransactionParams {
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
}
/**
 *
 * Request to submit an already-prepared ordinary ledger transaction to the ledger once, carrying every owner's collected signature for a Gnosis-Safe-like decentralized party -- Canton's interactive-submission execute endpoint accepts multiple owners' signatures for one party in a single call.
 *
 */
export interface ExecuteWithSignaturesParams {
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
    partyId: PartyId
    commandId: CommandId
    signatures: Signatures
}
/**
 *
 * Ledger API request structure
 *
 */
export interface LedgerApiParams {
    requestMethod: RequestMethod
    resource: Resource
    body?: Body
    query?: Query
    path?: Path
}
export interface StatusEvent {
    provider: Provider
    connection: ConnectResult
    network?: Network
    session?: Session
}
/**
 *
 * Represents a null value, used in responses where no data is returned.
 *
 */
export type Null = null
export interface PrepareExecuteResult {
    userUrl: UserUrl
}
export interface SignMessageResult {
    messageId: MessageId
    userUrl: UserUrl
}
export interface SignTopologyTransactionsResult {
    requestId: TopologyRequestId
    userUrl: UserUrl
}
export interface SignPreparedTransactionResult {
    requestId: PreparedTransactionRequestId
    userUrl: UserUrl
}
/**
 *
 * Raw ledger-API response from the combined executeAndWait submission.
 *
 */
export interface ExecuteWithSignaturesResult {
    [key: string]: any
}
/**
 *
 * Ledger Api response
 *
 */
export interface LedgerApiResult {
    [key: string]: any
}
/**
 *
 * Event emitted when the user's accounts change.
 *
 */
export type AccountsChangedEvent = Wallet[]
/**
 *
 * An array of accounts that the user has authorized the dapp to access..
 *
 */
export type ListAccountsResult = Wallet[]
/**
 *
 * Event emitted when a transaction changes.
 *
 */
export type TxChangedEvent =
    | TxChangedPendingEvent
    | TxChangedSignedEvent
    | TxChangedExecutedEvent
    | TxChangedFailedEvent
/**
 *
 * Event emitted when a message signature is requested or completed.
 *
 */
export type MessageSignatureEvent =
    | MessageSignaturePendingEvent
    | MessageSignatureSignedEvent
    | MessageSignatureFailedEvent
/**
 *
 * Event emitted when a topology-transactions bundle signature is requested or completed.
 *
 */
export type TopologyTransactionsSignatureEvent =
    | TopologyTransactionsSignaturePendingEvent
    | TopologyTransactionsSignatureSignedEvent
    | TopologyTransactionsSignatureFailedEvent
/**
 *
 * Event emitted when a signPreparedTransaction signature is requested or completed.
 *
 */
export type PreparedTransactionSignatureEvent =
    | PreparedTransactionSignaturePendingEvent
    | PreparedTransactionSignatureSignedEvent
    | PreparedTransactionSignatureFailedEvent
/**
 *
 * Generated! Represents an alias to any of the provided schemas
 *
 */

export type Status = () => Promise<StatusEvent>
export type Connect = () => Promise<ConnectResult>
export type Disconnect = () => Promise<Null>
export type IsConnected = () => Promise<ConnectResult>
export type GetActiveNetwork = () => Promise<Network>
export type PrepareExecute = (
    params: PrepareExecuteParams
) => Promise<PrepareExecuteResult>
export type SignMessage = (
    params: SignMessageParams
) => Promise<SignMessageResult>
export type SignTopologyTransactions = (
    params: SignTopologyTransactionsParams
) => Promise<SignTopologyTransactionsResult>
export type SignPreparedTransaction = (
    params: SignPreparedTransactionParams
) => Promise<SignPreparedTransactionResult>
export type ExecuteWithSignatures = (
    params: ExecuteWithSignaturesParams
) => Promise<ExecuteWithSignaturesResult>
export type LedgerApi = (params: LedgerApiParams) => Promise<LedgerApiResult>
export type Connected = () => Promise<StatusEvent>
export type OnStatusChanged = () => Promise<StatusEvent>
export type AccountsChanged = () => Promise<AccountsChangedEvent>
export type GetPrimaryAccount = () => Promise<Wallet>
export type ListAccounts = () => Promise<ListAccountsResult>
export type TxChanged = () => Promise<TxChangedEvent>
export type MessageSignature = () => Promise<MessageSignatureEvent>
export type TopologyTransactionsSignature =
    () => Promise<TopologyTransactionsSignatureEvent>
export type PreparedTransactionSignature =
    () => Promise<PreparedTransactionSignatureEvent>
/* eslint-enable @typescript-eslint/no-unused-vars */

type Params<T> = T extends (...args: infer A) => any
    ? A extends []
        ? never
        : A[0]
    : never
type Result<T> = T extends (...args: any[]) => Promise<infer R> ? R : never

export type RpcTypes = {
    status: {
        params: Params<Status>
        result: Result<Status>
    }

    connect: {
        params: Params<Connect>
        result: Result<Connect>
    }

    disconnect: {
        params: Params<Disconnect>
        result: Result<Disconnect>
    }

    isConnected: {
        params: Params<IsConnected>
        result: Result<IsConnected>
    }

    getActiveNetwork: {
        params: Params<GetActiveNetwork>
        result: Result<GetActiveNetwork>
    }

    prepareExecute: {
        params: Params<PrepareExecute>
        result: Result<PrepareExecute>
    }

    signMessage: {
        params: Params<SignMessage>
        result: Result<SignMessage>
    }

    signTopologyTransactions: {
        params: Params<SignTopologyTransactions>
        result: Result<SignTopologyTransactions>
    }

    signPreparedTransaction: {
        params: Params<SignPreparedTransaction>
        result: Result<SignPreparedTransaction>
    }

    executeWithSignatures: {
        params: Params<ExecuteWithSignatures>
        result: Result<ExecuteWithSignatures>
    }

    ledgerApi: {
        params: Params<LedgerApi>
        result: Result<LedgerApi>
    }

    connected: {
        params: Params<Connected>
        result: Result<Connected>
    }

    onStatusChanged: {
        params: Params<OnStatusChanged>
        result: Result<OnStatusChanged>
    }

    accountsChanged: {
        params: Params<AccountsChanged>
        result: Result<AccountsChanged>
    }

    getPrimaryAccount: {
        params: Params<GetPrimaryAccount>
        result: Result<GetPrimaryAccount>
    }

    listAccounts: {
        params: Params<ListAccounts>
        result: Result<ListAccounts>
    }

    txChanged: {
        params: Params<TxChanged>
        result: Result<TxChanged>
    }

    messageSignature: {
        params: Params<MessageSignature>
        result: Result<MessageSignature>
    }

    topologyTransactionsSignature: {
        params: Params<TopologyTransactionsSignature>
        result: Result<TopologyTransactionsSignature>
    }

    preparedTransactionSignature: {
        params: Params<PreparedTransactionSignature>
        result: Result<PreparedTransactionSignature>
    }
}

export class WalletJSONRPCRemoteDAppAPI {
    public transport: RpcTransport

    constructor(transport: RpcTransport) {
        this.transport = transport
    }

    public async request<M extends keyof RpcTypes>(
        args: RequestArgs<RpcTypes, M>
    ): Promise<RpcTypes[M]['result']> {
        const response = await this.transport.submit(args as RequestPayload)

        if ('error' in response) {
            throw new Error(
                'RPC error: ' +
                    response.error.code +
                    ' - ' +
                    response.error.message
            )
        } else {
            return response.result as RpcTypes[M]['result']
        }
    }
}
export default WalletJSONRPCRemoteDAppAPI
