// Code generated by @open-rpc/generator DO NOT EDIT.
import _ from 'lodash'

import { RequestArgs, RequestPayload } from '@canton-network/core-types'
import { RpcTransport } from '@canton-network/core-rpc-transport'

/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 *
 * The network ID the wallet corresponds to.
 *
 */
export type NetworkId = string
export type Name = string
/**
 *
 * Description of network
 *
 */
export type Description = string
/**
 *
 * Synchronizer ID
 *
 */
export type SynchronizerId = string
/**
 *
 * Identity Provider ID
 *
 */
export type IdentityProviderId = string
export type Method = string
export type Scope = string
export type ClientId = string
export type ClientSecret = string
/**
 *
 * Issuer of identity provider
 *
 */
export type Issuer = string
export type Audience = string
/**
 *
 * Represents the type of auth for a specified network
 *
 */
export interface Auth {
    method: Method
    scope: Scope
    clientId: ClientId
    clientSecret?: ClientSecret
    issuer?: Issuer
    audience: Audience
}
/**
 *
 * Ledger api url
 *
 */
export type LedgerApi = string
/**
 *
 * Connected network metadata. Privileged credentials (adminAuth, serviceAccountAuth) are included only for the admin user.
 *
 */
export interface Network {
    id: NetworkId
    name: Name
    description: Description
    synchronizerId?: SynchronizerId
    identityProviderId: IdentityProviderId
    auth: Auth
    adminAuth?: Auth
    serviceAccountAuth?: Auth
    ledgerApi: LedgerApi
}
/**
 *
 * Ledger api url
 *
 */
export type NetworkName = string
export type Id = string
/**
 *
 * Type of identity provider (oauth / self_signed)
 *
 */
export type Type = any
/**
 *
 * The configuration URL for the identity provider.
 *
 */
export type ConfigUrl = string
/**
 *
 * Structure representing the Identity Providers
 *
 */
export interface Idp {
    id: Id
    type: Type
    issuer: Issuer
    configUrl?: ConfigUrl
}
/**
 *
 * Set as primary wallet for dApp usage.
 *
 */
export type Primary = boolean
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type PartyHint = string
/**
 *
 * The signing provider ID the wallet corresponds to.
 *
 */
export type SigningProviderId = string
/**
 *
 * Name of signing provider's key to use for getting keys.
 *
 */
export type KeyName = string
/**
 *
 * The party ID corresponding to the wallet.
 *
 */
export type PartyId = string
/**
 *
 * Coordinator this party's signing is delegated to. Only meaningful for a wallet whose signingProviderId is 'decentralized': no single key in this gateway can authorize for such a party, so each signing request is parked and its owners are sent here to collect the signature set out of band.
 *
 */
export type DelegatedSigningUrl = string
/**
 *
 * Filter wallets by network IDs.
 *
 */
export type NetworkIds = NetworkId[]
/**
 *
 * Filter wallets by signing provider IDs.
 *
 */
export type SigningProviderIds = SigningProviderId[]
/**
 *
 * Filter for the wallets to be returned.
 *
 */
export interface WalletFilter {
    networkIds?: NetworkIds
    signingProviderIds?: SigningProviderIds
}
/**
 *
 * The internal transaction identifier.
 *
 */
export type TransactionId = string
/**
 *
 * The internal identifier of the pending message-signing request.
 *
 */
export type MessageId = string
/**
 *
 * The internal identifier of the pending topology-transactions signing request.
 *
 */
export type TopologyRequestId = string
/**
 *
 * The internal identifier of the pending signPreparedTransaction signing request.
 *
 */
export type PreparedTransactionRequestId = string
/**
 *
 * The signature over the transaction's hash.
 *
 */
export type Signature = string
/**
 *
 * Base64-encoded Ed25519 public key of the wallet that produced the signature.
 *
 */
export type SignedBy = string
/**
 *
 * The origin (dApp URL) that initiated this transaction request.
 *
 */
export type Origin = string
/**
 *
 * Limit of transactions to return.
 *
 */
export type Limit = number
/**
 *
 * Cursor for next page of results.
 *
 */
export type CursorAsString = string
/**
 *
 * Cursor for next page of results.
 *
 */
export type Cursor = CursorAsString
/**
 *
 * The public key of the party.
 *
 */
export type PublicKey = string
/**
 *
 * Authentication method configured for this network
 *
 */
export type AuthMethod = string
/**
 *
 * Network metadata exposed by listNetworks without sensitive auth configuration
 *
 */
export interface PublicNetwork {
    id: NetworkId
    name: Name
    description: Description
    synchronizerId?: SynchronizerId
    identityProviderId: IdentityProviderId
    ledgerApi: LedgerApi
    authMethod: AuthMethod
    clientId?: ClientId
    scope?: Scope
    audience?: Audience
}
export type Networks = PublicNetwork[]
/**
 *
 * The access token for the session.
 *
 */
export type AccessToken = string
export type Idps = Idp[]
/**
 *
 * The status of the wallet.
 *
 */
export type WalletStatus = 'initialized' | 'allocated' | 'removed'
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type Hint = string
/**
 *
 * The namespace of the party.
 *
 */
export type Namespace = string
/**
 *
 * Unique identifier of the signed transaction given by the Signing Provider. This may not be the same as the internal txId given by the Wallet Gateway.
 *
 */
export type ExternalTxId = string
/**
 *
 * The topology transactions
 *
 */
export type TopologyTransactions = string
/**
 *
 * Whether the wallet is disabled. Wallets are disabled when no signing provider matches the party's namespace during sync. Disabled wallets use participant as the default signing provider.
 *
 */
export type Disabled = boolean
/**
 *
 * Reason for the wallet state, e.g., 'no signing provider matched'.
 *
 */
export type Reason = string
export type PartyLevelRight = any
/**
 *
 * The rights of the wallet.
 *
 */
export type Rights = PartyLevelRight[]
/**
 *
 * Structure representing a wallet
 *
 */
export interface Wallet {
    primary: Primary
    partyId: PartyId
    status: WalletStatus
    hint: Hint
    publicKey: PublicKey
    namespace: Namespace
    networkId: NetworkId
    signingProviderId: SigningProviderId
    externalTxId?: ExternalTxId
    topologyTransactions?: TopologyTransactions
    disabled?: Disabled
    reason?: Reason
    delegatedSigningUrl?: DelegatedSigningUrl
    rights: Rights
}
type AlwaysTrue = any
/**
 *
 * Non-disabled wallets added in this syncWallets call.
 *
 */
export type SyncWalletsResultAdded = Wallet[]
/**
 *
 * Existing wallets that either got downgraded to status initialized or their rights changed in this syncWallets call.
 *
 */
export type SyncWalletsResultUpdated = Wallet[]
/**
 *
 * Either wallets added in this iteration that are disabled, or existing wallet that were updated to be disabled in this syncWallets call.
 *
 */
export type SyncWalletsResultDisabled = Wallet[]
/**
 *
 * Whether wallet sync is needed. Returns true if there are disabled wallets or parties on the ledger that aren't in the store.
 *
 */
export type WalletSyncNeeded = boolean
export type TxStatusSigned = 'signed'
export interface SignResultSigned {
    status: TxStatusSigned
    signature: Signature
    signedBy: SignedBy
    partyId: PartyId
    externalTxId?: ExternalTxId
}
export type TxStatusPending = 'pending'
/**
 *
 * Where a human must go to carry this signing request forward, when the provider needs one. Set by providers that delegate signing to an external coordinator (signingProviderId 'decentralized'); absent for providers that complete on their own, such as a custody service.
 *
 */
export type UserUrl = string
/**
 *
 * What the page at userUrl is, so a client can present it appropriately. 'approval' is this wallet's own short-lived approve/sign page for the calling user. 'handoff' is a different application, where other people take part and the user may stay for a while -- multi-owner coordination for a party whose signing is delegated. A browser client should give a handoff a normal tab rather than a small transient popup; a CLI or mobile client can act on the distinction too, which is why this says what the page IS rather than which window to use. Absent means 'approval'.
 *
 */
export type UserUrlKind = 'approval' | 'handoff'
export interface SignResultPending {
    status: TxStatusPending
    partyId: PartyId
    externalTxId: ExternalTxId
    userUrl?: UserUrl
    userUrlKind?: UserUrlKind
}
export type TxStatusRejected = 'rejected'
export interface SignResultRejected {
    status: TxStatusRejected
    partyId: PartyId
    externalTxId: ExternalTxId
}
export type TxStatusFailed = 'failed'
export interface SignResultFailed {
    status: TxStatusFailed
    partyId: PartyId
    externalTxId: ExternalTxId
}
/**
 *
 * The status of the transaction.
 *
 */
export type Status = string
/**
 *
 * The message to sign.
 *
 */
export type Message = string
/**
 *
 * The timestamp when the API key was created.
 *
 */
export type CreatedAt = string
/**
 *
 * The timestamp when the transaction was signed.
 *
 */
export type SignedAt = string
export interface MessageRaw {
    id: MessageId
    status: Status
    partyId: PartyId
    publicKey: PublicKey
    message: Message
    origin?: Origin
    createdAt: CreatedAt
    signedAt?: SignedAt
    signature?: Signature
}
export type Messages = MessageRaw[]
/**
 *
 * The multiHash actually signed, recomputed fresh at sign time.
 *
 */
export type MultiHash = string
export type TopologyTransactionBase64 = string
/**
 *
 * Base64-encoded, UntypedVersionedMessage-wrapped raw transaction bytes -- the source of truth the signature is computed from. Never trust the summaries below for signing.
 *
 */
export type TopologyBundleTransactions = TopologyTransactionBase64[]
export type Kind =
    | 'namespaceDelegation'
    | 'decentralizedNamespaceDefinition'
    | 'partyToParticipant'
    | 'partyToKeyMapping'
    | 'unknown'
/**
 *
 * Set when kind is namespaceDelegation.
 *
 */
export type IsRootDelegation = boolean
/**
 *
 * Set when kind is decentralizedNamespaceDefinition.
 *
 */
export type DecentralizedNamespace = string
/**
 *
 * Set when kind is decentralizedNamespaceDefinition, partyToParticipant, or partyToKeyMapping.
 *
 */
export type Threshold = number
export type OwnerFingerprint = string
/**
 *
 * Set when kind is decentralizedNamespaceDefinition.
 *
 */
export type Owners = OwnerFingerprint[]
/**
 *
 * Set when kind is partyToParticipant or partyToKeyMapping.
 *
 */
export type Party = string
export type ParticipantUid = string
export type Permission = number
export interface TopologyHostingParticipant {
    participantUid: ParticipantUid
    permission: Permission
}
/**
 *
 * Set when kind is partyToParticipant.
 *
 */
export type Participants = TopologyHostingParticipant[]
/**
 *
 * Set when kind is partyToKeyMapping.
 *
 */
export type SigningKeyCount = number
/**
 *
 * Set when kind is unknown: the raw TopologyMapping oneofKind that isn't recognized.
 *
 */
export type MappingKind = string
/**
 *
 * Decoded, display-only summary of one topology transaction within a signing bundle. Never used for hashing/signing -- only the raw stored bytes are.
 *
 */
export interface TopologyTransactionSummary {
    kind: Kind
    namespace?: Namespace
    isRootDelegation?: IsRootDelegation
    decentralizedNamespace?: DecentralizedNamespace
    threshold?: Threshold
    owners?: Owners
    party?: Party
    participants?: Participants
    signingKeyCount?: SigningKeyCount
    mappingKind?: MappingKind
}
/**
 *
 * Decoded, display-only summary of each transaction, computed once at receipt time.
 *
 */
export type Summaries = TopologyTransactionSummary[]
export interface TopologyBundleRaw {
    id: TopologyRequestId
    status: Status
    partyId: PartyId
    publicKey: PublicKey
    transactions: TopologyBundleTransactions
    summaries: Summaries
    synchronizerId?: SynchronizerId
    origin?: Origin
    createdAt: CreatedAt
    signedAt?: SignedAt
    signature?: Signature
    multiHash?: MultiHash
}
export type Bundles = TopologyBundleRaw[]
/**
 *
 * The transaction data corresponding to the command ID.
 *
 */
export type PreparedTransaction = string
export interface PreparedTransactionToSign {
    id: PreparedTransactionRequestId
    status: Status
    partyId: PartyId
    publicKey: PublicKey
    preparedTransaction: PreparedTransaction
    origin?: Origin
    createdAt: CreatedAt
    signedAt?: SignedAt
    signature?: Signature
}
export type UserLevelRight = any
/**
 *
 * Structure representing the connected network session
 *
 */
export interface Session {
    id: Id
    origin?: Origin
    network: Network
    idp: Idp
    accessToken: AccessToken
    status: Status
    reason?: Reason
    rights: Rights
}
export type Sessions = Session[]
/**
 *
 * The unique identifier of the command associated with the transaction.
 *
 */
export type CommandId = string
/**
 *
 * The hash of the prepared transaction.
 *
 */
export type PreparedTransactionHash = string
/**
 *
 * Optional payload associated with the transaction.
 *
 */
export type Payload = string
export interface Transaction {
    id: TransactionId
    commandId: CommandId
    status: Status
    createdAt?: CreatedAt
    signedAt?: SignedAt
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
    payload?: Payload
    origin?: Origin
    externalTxId?: ExternalTxId
}
export type Transactions = Transaction[]
/**
 *
 * Cursor for next page of results.
 *
 */
export type NextCursor = string
/**
 *
 * Number of total transactions for the user.
 *
 */
export type Count = number
/**
 *
 * The unique identifier of the current user.
 *
 */
export type UserIdentifier = string
/**
 *
 * Whether the current user is an admin.
 *
 */
export type IsAdminFlag = boolean
/**
 *
 * The generated API key.
 *
 */
export type ApiKeyResult = string
export interface ApiKey {
    id: Id
    name: Name
    createdAt: CreatedAt
}
/**
 *
 * The list of API keys.
 *
 */
export type ApiKeys = ApiKey[]
export interface Key {
    id: Id
    name: Name
    publicKey: PublicKey
}
/**
 *
 * The list of signing provider's available keys.
 *
 */
export type Keys = Key[]
/**
 *
 * Represents a null value, used in responses where no data is returned.
 *
 */
export type Null = null
export interface AddNetworkParams {
    network: Network
}
export interface RemoveNetworkParams {
    networkName: NetworkName
}
export interface GetNetworkParams {
    networkId: NetworkId
}
export interface SelfSignedAccessTokenParams {
    networkId: NetworkId
    clientId: ClientId
    clientSecret: ClientSecret
}
export interface AddIdpParams {
    idp: Idp
}
export interface RemoveIdpParams {
    identityProviderId: IdentityProviderId
}
export interface CreateWalletParams {
    primary?: Primary
    partyHint: PartyHint
    signingProviderId: SigningProviderId
    keyName?: KeyName
}
export interface AllocatePartyForWalletParams {
    partyId: PartyId
}
export interface ImportPartyParams {
    partyId: PartyId
    delegatedSigningUrl?: DelegatedSigningUrl
}
export interface SetDelegatedSigningParams {
    partyId: PartyId
    delegatedSigningUrl: DelegatedSigningUrl
}
export interface SetPrimaryWalletParams {
    partyId: PartyId
}
export interface RemoveWalletParams {
    partyId: PartyId
}
export interface ListWalletsParams {
    filter?: WalletFilter
}
export interface SignParams {
    transactionId: TransactionId
    partyId: PartyId
}
export interface SignMessageParams {
    messageId: MessageId
    partyId?: PartyId
}
export interface GetMessageToSignParams {
    messageId: MessageId
}
export interface DeleteMessageToSignParams {
    messageId: MessageId
}
export interface SignTopologyTransactionsParams {
    requestId: TopologyRequestId
}
export interface SignPreparedTransactionParams {
    requestId: PreparedTransactionRequestId
}
export interface GetTopologyBundleToSignParams {
    requestId: TopologyRequestId
}
export interface DeleteTopologyBundleToSignParams {
    requestId: TopologyRequestId
}
export interface GetPreparedTransactionToSignParams {
    requestId: PreparedTransactionRequestId
}
export interface DeletePreparedTransactionToSignParams {
    requestId: PreparedTransactionRequestId
}
export interface ExecuteParams {
    signature: Signature
    partyId: PartyId
    transactionId: TransactionId
    signedBy: SignedBy
}
export interface AddSessionParams {
    origin: Origin
    networkId: NetworkId
}
export interface GetTransactionParams {
    transactionId: TransactionId
}
export interface ListTransactionsParams {
    limit?: Limit
    cursor?: Cursor
}
export interface DeleteTransactionParams {
    transactionId: TransactionId
}
export interface GenerateApiKeyParams {
    name: Name
}
export interface RemoveApiKeyParams {
    id: Id
}
export interface ListSigningProviderKeysParams {
    signingProviderId: SigningProviderId
}
export interface GetWalletParams {
    partyId: PartyId
}
export interface ChangeSigningProviderParams {
    signingProviderId: SigningProviderId
    partyId: PartyId
    publicKey: PublicKey
}
export interface ListNetworksResult {
    networks: Networks
}
export interface GetNetworkResult {
    network: Network
}
export interface SelfSignedAccessTokenResult {
    accessToken: AccessToken
}
export interface ListIdpsResult {
    idps: Idps
}
export interface CreateWalletResult {
    wallet: Wallet
}
export interface AllocatePartyForWalletResult {
    wallet: Wallet
}
export interface ImportPartyResult {
    wallet: Wallet
}
export interface SetDelegatedSigningResult {
    wallet: Wallet
}
export interface RemovePartyResult {
    [key: string]: any
}
/**
 *
 * An array of wallets that match the filter criteria.
 *
 */
export type ListWalletsResult = Wallet[]
/**
 *
 * Added, updated  and disabled wallets as a result of the sync.
 *
 */
export interface SyncWalletsResult {
    added: SyncWalletsResultAdded
    updated: SyncWalletsResultUpdated
    disabled: SyncWalletsResultDisabled
}
export interface IsWalletSyncNeededResult {
    walletSyncNeeded: WalletSyncNeeded
}
export type SignResult =
    SignResultSigned | SignResultPending | SignResultRejected | SignResultFailed
export interface SignMessageResult {
    signature: Signature
    publicKey: PublicKey
}
export interface GetMessageToSignResult {
    message: MessageRaw
}
export interface ListMessagesToSignResult {
    messages: Messages
}
export interface SignTopologyTransactionsResult {
    signature: Signature
    publicKey: PublicKey
    multiHash: MultiHash
}
export interface SignPreparedTransactionResult {
    signature: Signature
    signedBy: SignedBy
}
export interface GetTopologyBundleToSignResult {
    bundle: TopologyBundleRaw
}
export interface ListTopologyBundlesToSignResult {
    bundles: Bundles
}
export interface GetPreparedTransactionToSignResult {
    record: PreparedTransactionToSign
}
export interface ExecuteResult {
    [key: string]: any
}
/**
 *
 * Structure representing the connected network session
 *
 */
export interface AddSessionResult {
    id: Id
    origin?: Origin
    network: Network
    idp: Idp
    accessToken: AccessToken
    status: Status
    reason?: Reason
    rights: Rights
}
export interface ListSessionsResult {
    sessions: Sessions
}
export interface GetTransactionResult {
    id: TransactionId
    commandId: CommandId
    status: Status
    createdAt?: CreatedAt
    signedAt?: SignedAt
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
    payload?: Payload
    origin?: Origin
    externalTxId?: ExternalTxId
}
export interface ListTransactionsResult {
    transactions: Transactions
    nextCursor?: NextCursor
    count: Count
}
export interface GetUserResult {
    userId: UserIdentifier
    isAdmin: IsAdminFlag
}
export interface GeneratedApiKey {
    id: Id
    apiKey: ApiKeyResult
}
export interface ListApiKeysResult {
    apiKeys: ApiKeys
}
export interface ListSigningProviderKeysResult {
    keys: Keys
}
export type GetWalletResult = Wallet | Null
/**
 *
 * Generated! Represents an alias to any of the provided schemas
 *
 */

export type AddNetwork = (params: AddNetworkParams) => Promise<Null>
export type RemoveNetwork = (params: RemoveNetworkParams) => Promise<Null>
export type ListNetworks = () => Promise<ListNetworksResult>
export type GetNetwork = (params: GetNetworkParams) => Promise<GetNetworkResult>
export type SelfSignedAccessToken = (
    params: SelfSignedAccessTokenParams
) => Promise<SelfSignedAccessTokenResult>
export type AddIdp = (params: AddIdpParams) => Promise<Null>
export type RemoveIdp = (params: RemoveIdpParams) => Promise<Null>
export type ListIdps = () => Promise<ListIdpsResult>
export type CreateWallet = (
    params: CreateWalletParams
) => Promise<CreateWalletResult>
export type AllocatePartyForWallet = (
    params: AllocatePartyForWalletParams
) => Promise<AllocatePartyForWalletResult>
export type ImportParty = (
    params: ImportPartyParams
) => Promise<ImportPartyResult>
export type SetDelegatedSigning = (
    params: SetDelegatedSigningParams
) => Promise<SetDelegatedSigningResult>
export type SetPrimaryWallet = (params: SetPrimaryWalletParams) => Promise<Null>
export type RemoveWallet = (
    params: RemoveWalletParams
) => Promise<RemovePartyResult>
export type ListWallets = (
    params: ListWalletsParams
) => Promise<ListWalletsResult>
export type SyncWallets = () => Promise<SyncWalletsResult>
export type IsWalletSyncNeeded = () => Promise<IsWalletSyncNeededResult>
export type Sign = (params: SignParams) => Promise<SignResult>
export type SignMessage = (
    params: SignMessageParams
) => Promise<SignMessageResult>
export type GetMessageToSign = (
    params: GetMessageToSignParams
) => Promise<GetMessageToSignResult>
export type ListMessagesToSign = () => Promise<ListMessagesToSignResult>
export type DeleteMessageToSign = (
    params: DeleteMessageToSignParams
) => Promise<Null>
export type SignTopologyTransactions = (
    params: SignTopologyTransactionsParams
) => Promise<SignTopologyTransactionsResult>
export type SignPreparedTransaction = (
    params: SignPreparedTransactionParams
) => Promise<SignPreparedTransactionResult>
export type GetTopologyBundleToSign = (
    params: GetTopologyBundleToSignParams
) => Promise<GetTopologyBundleToSignResult>
export type ListTopologyBundlesToSign =
    () => Promise<ListTopologyBundlesToSignResult>
export type DeleteTopologyBundleToSign = (
    params: DeleteTopologyBundleToSignParams
) => Promise<Null>
export type GetPreparedTransactionToSign = (
    params: GetPreparedTransactionToSignParams
) => Promise<GetPreparedTransactionToSignResult>
export type DeletePreparedTransactionToSign = (
    params: DeletePreparedTransactionToSignParams
) => Promise<Null>
export type Execute = (params: ExecuteParams) => Promise<ExecuteResult>
export type AddSession = (params: AddSessionParams) => Promise<AddSessionResult>
export type RemoveSession = () => Promise<Null>
export type ListSessions = () => Promise<ListSessionsResult>
export type GetTransaction = (
    params: GetTransactionParams
) => Promise<GetTransactionResult>
export type ListTransactions = (
    params: ListTransactionsParams
) => Promise<ListTransactionsResult>
export type DeleteTransaction = (
    params: DeleteTransactionParams
) => Promise<Null>
export type GetUser = () => Promise<GetUserResult>
export type GenerateApiKey = (
    params: GenerateApiKeyParams
) => Promise<GeneratedApiKey>
export type ListApiKeys = () => Promise<ListApiKeysResult>
export type RemoveApiKey = (params: RemoveApiKeyParams) => Promise<Null>
export type ListSigningProviderKeys = (
    params: ListSigningProviderKeysParams
) => Promise<ListSigningProviderKeysResult>
export type GetWallet = (params: GetWalletParams) => Promise<GetWalletResult>
export type ChangeSigningProvider = (
    params: ChangeSigningProviderParams
) => Promise<Null>
/* eslint-enable @typescript-eslint/no-unused-vars */

type Params<T> = T extends (...args: infer A) => any
    ? A extends []
        ? never
        : A[0]
    : never
type Result<T> = T extends (...args: any[]) => Promise<infer R> ? R : never

export type RpcTypes = {
    addNetwork: {
        params: Params<AddNetwork>
        result: Result<AddNetwork>
    }

    removeNetwork: {
        params: Params<RemoveNetwork>
        result: Result<RemoveNetwork>
    }

    listNetworks: {
        params: Params<ListNetworks>
        result: Result<ListNetworks>
    }

    getNetwork: {
        params: Params<GetNetwork>
        result: Result<GetNetwork>
    }

    selfSignedAccessToken: {
        params: Params<SelfSignedAccessToken>
        result: Result<SelfSignedAccessToken>
    }

    addIdp: {
        params: Params<AddIdp>
        result: Result<AddIdp>
    }

    removeIdp: {
        params: Params<RemoveIdp>
        result: Result<RemoveIdp>
    }

    listIdps: {
        params: Params<ListIdps>
        result: Result<ListIdps>
    }

    createWallet: {
        params: Params<CreateWallet>
        result: Result<CreateWallet>
    }

    allocatePartyForWallet: {
        params: Params<AllocatePartyForWallet>
        result: Result<AllocatePartyForWallet>
    }

    importParty: {
        params: Params<ImportParty>
        result: Result<ImportParty>
    }

    setDelegatedSigning: {
        params: Params<SetDelegatedSigning>
        result: Result<SetDelegatedSigning>
    }

    setPrimaryWallet: {
        params: Params<SetPrimaryWallet>
        result: Result<SetPrimaryWallet>
    }

    removeWallet: {
        params: Params<RemoveWallet>
        result: Result<RemoveWallet>
    }

    listWallets: {
        params: Params<ListWallets>
        result: Result<ListWallets>
    }

    syncWallets: {
        params: Params<SyncWallets>
        result: Result<SyncWallets>
    }

    isWalletSyncNeeded: {
        params: Params<IsWalletSyncNeeded>
        result: Result<IsWalletSyncNeeded>
    }

    sign: {
        params: Params<Sign>
        result: Result<Sign>
    }

    signMessage: {
        params: Params<SignMessage>
        result: Result<SignMessage>
    }

    getMessageToSign: {
        params: Params<GetMessageToSign>
        result: Result<GetMessageToSign>
    }

    listMessagesToSign: {
        params: Params<ListMessagesToSign>
        result: Result<ListMessagesToSign>
    }

    deleteMessageToSign: {
        params: Params<DeleteMessageToSign>
        result: Result<DeleteMessageToSign>
    }

    signTopologyTransactions: {
        params: Params<SignTopologyTransactions>
        result: Result<SignTopologyTransactions>
    }

    signPreparedTransaction: {
        params: Params<SignPreparedTransaction>
        result: Result<SignPreparedTransaction>
    }

    getTopologyBundleToSign: {
        params: Params<GetTopologyBundleToSign>
        result: Result<GetTopologyBundleToSign>
    }

    listTopologyBundlesToSign: {
        params: Params<ListTopologyBundlesToSign>
        result: Result<ListTopologyBundlesToSign>
    }

    deleteTopologyBundleToSign: {
        params: Params<DeleteTopologyBundleToSign>
        result: Result<DeleteTopologyBundleToSign>
    }

    getPreparedTransactionToSign: {
        params: Params<GetPreparedTransactionToSign>
        result: Result<GetPreparedTransactionToSign>
    }

    deletePreparedTransactionToSign: {
        params: Params<DeletePreparedTransactionToSign>
        result: Result<DeletePreparedTransactionToSign>
    }

    execute: {
        params: Params<Execute>
        result: Result<Execute>
    }

    addSession: {
        params: Params<AddSession>
        result: Result<AddSession>
    }

    removeSession: {
        params: Params<RemoveSession>
        result: Result<RemoveSession>
    }

    listSessions: {
        params: Params<ListSessions>
        result: Result<ListSessions>
    }

    getTransaction: {
        params: Params<GetTransaction>
        result: Result<GetTransaction>
    }

    listTransactions: {
        params: Params<ListTransactions>
        result: Result<ListTransactions>
    }

    deleteTransaction: {
        params: Params<DeleteTransaction>
        result: Result<DeleteTransaction>
    }

    getUser: {
        params: Params<GetUser>
        result: Result<GetUser>
    }

    generateApiKey: {
        params: Params<GenerateApiKey>
        result: Result<GenerateApiKey>
    }

    listApiKeys: {
        params: Params<ListApiKeys>
        result: Result<ListApiKeys>
    }

    removeApiKey: {
        params: Params<RemoveApiKey>
        result: Result<RemoveApiKey>
    }

    listSigningProviderKeys: {
        params: Params<ListSigningProviderKeys>
        result: Result<ListSigningProviderKeys>
    }

    getWallet: {
        params: Params<GetWallet>
        result: Result<GetWallet>
    }

    changeSigningProvider: {
        params: Params<ChangeSigningProvider>
        result: Result<ChangeSigningProvider>
    }
}

export class WalletJSONRPCUserAPI {
    public transport: RpcTransport

    constructor(transport: RpcTransport) {
        this.transport = transport
    }

    public async request<M extends keyof RpcTypes>(
        args: RequestArgs<RpcTypes, M>
    ): Promise<RpcTypes[M]['result']> {
        const response = await this.transport.submit(args as RequestPayload)

        if ('error' in response) {
            throw new Error(
                'RPC error: ' +
                    response.error.code +
                    ' - ' +
                    response.error.message
            )
        } else {
            return response.result as RpcTypes[M]['result']
        }
    }
}
export default WalletJSONRPCUserAPI
