// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "com/digitalasset/canton/topology/admin/v30/common.proto" (package "com.digitalasset.canton.topology.admin.v30", syntax proto3)
// tslint:disable
//
// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
import type { BinaryWriteOptions } from '@protobuf-ts/runtime'
import type { IBinaryWriter } from '@protobuf-ts/runtime'
import { WireType } from '@protobuf-ts/runtime'
import type { BinaryReadOptions } from '@protobuf-ts/runtime'
import type { IBinaryReader } from '@protobuf-ts/runtime'
import { UnknownFieldHandler } from '@protobuf-ts/runtime'
import type { PartialMessage } from '@protobuf-ts/runtime'
import { reflectionMergePartial } from '@protobuf-ts/runtime'
import { MessageType } from '@protobuf-ts/runtime'
import { Timestamp } from '../../../../../../google/protobuf/timestamp.js'
/**
 * * Topology transaction collection used during bootstrapping of synchronizer nodes and on the admin API
 *
 * Please note that this message should not be in the protocol package, as it is not used on the protocol
 * itself but on the admin apis. But as we can't rename the package name due to backwards compatibility
 * guarantees, we've moved the file out of the protocol.proto file, but kept the package name.
 *
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.TopologyTransactions
 */
export interface TopologyTransactions {
    /**
     * @generated from protobuf field: repeated com.digitalasset.canton.topology.admin.v30.TopologyTransactions.Item items = 1
     */
    items: TopologyTransactions_Item[]
}
/**
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.TopologyTransactions.Item
 */
export interface TopologyTransactions_Item {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp sequenced = 4
     */
    sequenced?: Timestamp
    /**
     * @generated from protobuf field: google.protobuf.Timestamp valid_from = 1
     */
    validFrom?: Timestamp
    /**
     * @generated from protobuf field: google.protobuf.Timestamp valid_until = 2
     */
    validUntil?: Timestamp
    /**
     * * Versioned signed topology transactions serialized as byte-strings. Note that we use here the serialized
     * version that contains the version number. Using the "Versioned" version directly here would create a circular
     * dependency between the proto files. The only proper solution would be to move this into a third separate file
     * with "cross version data files", which we might do at some point.
     *
     * @generated from protobuf field: bytes transaction = 3
     */
    transaction: Uint8Array
    /**
     * @generated from protobuf field: optional string rejection_reason = 5
     */
    rejectionReason?: string
}
/**
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.Synchronizer
 */
export interface Synchronizer {
    /**
     * @generated from protobuf oneof: kind
     */
    kind:
        | {
              oneofKind: 'id'
              /**
               * @generated from protobuf field: string id = 1
               */
              id: string
          }
        | {
              oneofKind: 'physicalId'
              /**
               * @generated from protobuf field: string physical_id = 2
               */
              physicalId: string
          }
        | {
              oneofKind: undefined
          }
}
/**
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.StoreId
 */
export interface StoreId {
    /**
     * @generated from protobuf oneof: store
     */
    store:
        | {
              oneofKind: 'authorized'
              /**
               * @generated from protobuf field: com.digitalasset.canton.topology.admin.v30.StoreId.Authorized authorized = 1
               */
              authorized: StoreId_Authorized
          }
        | {
              oneofKind: 'synchronizer'
              /**
               * @generated from protobuf field: com.digitalasset.canton.topology.admin.v30.Synchronizer synchronizer = 2
               */
              synchronizer: Synchronizer
          }
        | {
              oneofKind: 'temporary'
              /**
               * @generated from protobuf field: com.digitalasset.canton.topology.admin.v30.StoreId.Temporary temporary = 3
               */
              temporary: StoreId_Temporary
          }
        | {
              oneofKind: undefined
          }
}
/**
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.StoreId.Authorized
 */
export interface StoreId_Authorized {}
/**
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.StoreId.Temporary
 */
export interface StoreId_Temporary {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string
}
/**
 * @generated from protobuf message com.digitalasset.canton.topology.admin.v30.SynchronizerPredecessor
 */
export interface SynchronizerPredecessor {
    /**
     * Id of the predecessor.
     *
     * @generated from protobuf field: string predecessor_physical_id = 1
     */
    predecessorPhysicalId: string
    /**
     * When the upgrade happened/is supposed to happen.
     *
     * @generated from protobuf field: google.protobuf.Timestamp upgrade_time = 2
     */
    upgradeTime?: Timestamp
    /**
     * Whether the participant is performing a late synchronizer upgrade.
     * default: false
     *
     * @generated from protobuf field: bool is_late_upgrade = 3
     */
    isLateUpgrade: boolean
}
// @generated message type with reflection information, may provide speed optimized methods
class TopologyTransactions$Type extends MessageType<TopologyTransactions> {
    constructor() {
        super(
            'com.digitalasset.canton.topology.admin.v30.TopologyTransactions',
            [
                {
                    no: 1,
                    name: 'items',
                    kind: 'message',
                    repeat: 2 /*RepeatType.UNPACKED*/,
                    T: () => TopologyTransactions_Item,
                },
            ]
        )
    }
    create(value?: PartialMessage<TopologyTransactions>): TopologyTransactions {
        const message = globalThis.Object.create(this.messagePrototype!)
        message.items = []
        if (value !== undefined)
            reflectionMergePartial<TopologyTransactions>(this, message, value)
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: TopologyTransactions
    ): TopologyTransactions {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                case /* repeated com.digitalasset.canton.topology.admin.v30.TopologyTransactions.Item items */ 1:
                    message.items.push(
                        TopologyTransactions_Item.internalBinaryRead(
                            reader,
                            reader.uint32(),
                            options
                        )
                    )
                    break
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: TopologyTransactions,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        /* repeated com.digitalasset.canton.topology.admin.v30.TopologyTransactions.Item items = 1; */
        for (let i = 0; i < message.items.length; i++)
            TopologyTransactions_Item.internalBinaryWrite(
                message.items[i],
                writer.tag(1, WireType.LengthDelimited).fork(),
                options
            ).join()
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.TopologyTransactions
 */
export const TopologyTransactions = new TopologyTransactions$Type()
// @generated message type with reflection information, may provide speed optimized methods
class TopologyTransactions_Item$Type extends MessageType<TopologyTransactions_Item> {
    constructor() {
        super(
            'com.digitalasset.canton.topology.admin.v30.TopologyTransactions.Item',
            [
                {
                    no: 4,
                    name: 'sequenced',
                    kind: 'message',
                    T: () => Timestamp,
                },
                {
                    no: 1,
                    name: 'valid_from',
                    kind: 'message',
                    T: () => Timestamp,
                },
                {
                    no: 2,
                    name: 'valid_until',
                    kind: 'message',
                    T: () => Timestamp,
                },
                {
                    no: 3,
                    name: 'transaction',
                    kind: 'scalar',
                    T: 12 /*ScalarType.BYTES*/,
                },
                {
                    no: 5,
                    name: 'rejection_reason',
                    kind: 'scalar',
                    opt: true,
                    T: 9 /*ScalarType.STRING*/,
                },
            ]
        )
    }
    create(
        value?: PartialMessage<TopologyTransactions_Item>
    ): TopologyTransactions_Item {
        const message = globalThis.Object.create(this.messagePrototype!)
        message.transaction = new Uint8Array(0)
        if (value !== undefined)
            reflectionMergePartial<TopologyTransactions_Item>(
                this,
                message,
                value
            )
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: TopologyTransactions_Item
    ): TopologyTransactions_Item {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                case /* google.protobuf.Timestamp sequenced */ 4:
                    message.sequenced = Timestamp.internalBinaryRead(
                        reader,
                        reader.uint32(),
                        options,
                        message.sequenced
                    )
                    break
                case /* google.protobuf.Timestamp valid_from */ 1:
                    message.validFrom = Timestamp.internalBinaryRead(
                        reader,
                        reader.uint32(),
                        options,
                        message.validFrom
                    )
                    break
                case /* google.protobuf.Timestamp valid_until */ 2:
                    message.validUntil = Timestamp.internalBinaryRead(
                        reader,
                        reader.uint32(),
                        options,
                        message.validUntil
                    )
                    break
                case /* bytes transaction */ 3:
                    message.transaction = reader.bytes()
                    break
                case /* optional string rejection_reason */ 5:
                    message.rejectionReason = reader.string()
                    break
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: TopologyTransactions_Item,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        /* google.protobuf.Timestamp valid_from = 1; */
        if (message.validFrom)
            Timestamp.internalBinaryWrite(
                message.validFrom,
                writer.tag(1, WireType.LengthDelimited).fork(),
                options
            ).join()
        /* google.protobuf.Timestamp valid_until = 2; */
        if (message.validUntil)
            Timestamp.internalBinaryWrite(
                message.validUntil,
                writer.tag(2, WireType.LengthDelimited).fork(),
                options
            ).join()
        /* bytes transaction = 3; */
        if (message.transaction.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.transaction)
        /* google.protobuf.Timestamp sequenced = 4; */
        if (message.sequenced)
            Timestamp.internalBinaryWrite(
                message.sequenced,
                writer.tag(4, WireType.LengthDelimited).fork(),
                options
            ).join()
        /* optional string rejection_reason = 5; */
        if (message.rejectionReason !== undefined)
            writer
                .tag(5, WireType.LengthDelimited)
                .string(message.rejectionReason)
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.TopologyTransactions.Item
 */
export const TopologyTransactions_Item = new TopologyTransactions_Item$Type()
// @generated message type with reflection information, may provide speed optimized methods
class Synchronizer$Type extends MessageType<Synchronizer> {
    constructor() {
        super('com.digitalasset.canton.topology.admin.v30.Synchronizer', [
            {
                no: 1,
                name: 'id',
                kind: 'scalar',
                oneof: 'kind',
                T: 9 /*ScalarType.STRING*/,
            },
            {
                no: 2,
                name: 'physical_id',
                kind: 'scalar',
                oneof: 'kind',
                T: 9 /*ScalarType.STRING*/,
            },
        ])
    }
    create(value?: PartialMessage<Synchronizer>): Synchronizer {
        const message = globalThis.Object.create(this.messagePrototype!)
        message.kind = { oneofKind: undefined }
        if (value !== undefined)
            reflectionMergePartial<Synchronizer>(this, message, value)
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: Synchronizer
    ): Synchronizer {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                case /* string id */ 1:
                    message.kind = {
                        oneofKind: 'id',
                        id: reader.string(),
                    }
                    break
                case /* string physical_id */ 2:
                    message.kind = {
                        oneofKind: 'physicalId',
                        physicalId: reader.string(),
                    }
                    break
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: Synchronizer,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        /* string id = 1; */
        if (message.kind.oneofKind === 'id')
            writer.tag(1, WireType.LengthDelimited).string(message.kind.id)
        /* string physical_id = 2; */
        if (message.kind.oneofKind === 'physicalId')
            writer
                .tag(2, WireType.LengthDelimited)
                .string(message.kind.physicalId)
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.Synchronizer
 */
export const Synchronizer = new Synchronizer$Type()
// @generated message type with reflection information, may provide speed optimized methods
class StoreId$Type extends MessageType<StoreId> {
    constructor() {
        super('com.digitalasset.canton.topology.admin.v30.StoreId', [
            {
                no: 1,
                name: 'authorized',
                kind: 'message',
                oneof: 'store',
                T: () => StoreId_Authorized,
            },
            {
                no: 2,
                name: 'synchronizer',
                kind: 'message',
                oneof: 'store',
                T: () => Synchronizer,
            },
            {
                no: 3,
                name: 'temporary',
                kind: 'message',
                oneof: 'store',
                T: () => StoreId_Temporary,
            },
        ])
    }
    create(value?: PartialMessage<StoreId>): StoreId {
        const message = globalThis.Object.create(this.messagePrototype!)
        message.store = { oneofKind: undefined }
        if (value !== undefined)
            reflectionMergePartial<StoreId>(this, message, value)
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: StoreId
    ): StoreId {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                case /* com.digitalasset.canton.topology.admin.v30.StoreId.Authorized authorized */ 1:
                    message.store = {
                        oneofKind: 'authorized',
                        authorized: StoreId_Authorized.internalBinaryRead(
                            reader,
                            reader.uint32(),
                            options,
                            (message.store as any).authorized
                        ),
                    }
                    break
                case /* com.digitalasset.canton.topology.admin.v30.Synchronizer synchronizer */ 2:
                    message.store = {
                        oneofKind: 'synchronizer',
                        synchronizer: Synchronizer.internalBinaryRead(
                            reader,
                            reader.uint32(),
                            options,
                            (message.store as any).synchronizer
                        ),
                    }
                    break
                case /* com.digitalasset.canton.topology.admin.v30.StoreId.Temporary temporary */ 3:
                    message.store = {
                        oneofKind: 'temporary',
                        temporary: StoreId_Temporary.internalBinaryRead(
                            reader,
                            reader.uint32(),
                            options,
                            (message.store as any).temporary
                        ),
                    }
                    break
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: StoreId,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        /* com.digitalasset.canton.topology.admin.v30.StoreId.Authorized authorized = 1; */
        if (message.store.oneofKind === 'authorized')
            StoreId_Authorized.internalBinaryWrite(
                message.store.authorized,
                writer.tag(1, WireType.LengthDelimited).fork(),
                options
            ).join()
        /* com.digitalasset.canton.topology.admin.v30.Synchronizer synchronizer = 2; */
        if (message.store.oneofKind === 'synchronizer')
            Synchronizer.internalBinaryWrite(
                message.store.synchronizer,
                writer.tag(2, WireType.LengthDelimited).fork(),
                options
            ).join()
        /* com.digitalasset.canton.topology.admin.v30.StoreId.Temporary temporary = 3; */
        if (message.store.oneofKind === 'temporary')
            StoreId_Temporary.internalBinaryWrite(
                message.store.temporary,
                writer.tag(3, WireType.LengthDelimited).fork(),
                options
            ).join()
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.StoreId
 */
export const StoreId = new StoreId$Type()
// @generated message type with reflection information, may provide speed optimized methods
class StoreId_Authorized$Type extends MessageType<StoreId_Authorized> {
    constructor() {
        super(
            'com.digitalasset.canton.topology.admin.v30.StoreId.Authorized',
            []
        )
    }
    create(value?: PartialMessage<StoreId_Authorized>): StoreId_Authorized {
        const message = globalThis.Object.create(this.messagePrototype!)
        if (value !== undefined)
            reflectionMergePartial<StoreId_Authorized>(this, message, value)
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: StoreId_Authorized
    ): StoreId_Authorized {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: StoreId_Authorized,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.StoreId.Authorized
 */
export const StoreId_Authorized = new StoreId_Authorized$Type()
// @generated message type with reflection information, may provide speed optimized methods
class StoreId_Temporary$Type extends MessageType<StoreId_Temporary> {
    constructor() {
        super('com.digitalasset.canton.topology.admin.v30.StoreId.Temporary', [
            { no: 1, name: 'name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
        ])
    }
    create(value?: PartialMessage<StoreId_Temporary>): StoreId_Temporary {
        const message = globalThis.Object.create(this.messagePrototype!)
        message.name = ''
        if (value !== undefined)
            reflectionMergePartial<StoreId_Temporary>(this, message, value)
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: StoreId_Temporary
    ): StoreId_Temporary {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string()
                    break
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: StoreId_Temporary,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== '')
            writer.tag(1, WireType.LengthDelimited).string(message.name)
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.StoreId.Temporary
 */
export const StoreId_Temporary = new StoreId_Temporary$Type()
// @generated message type with reflection information, may provide speed optimized methods
class SynchronizerPredecessor$Type extends MessageType<SynchronizerPredecessor> {
    constructor() {
        super(
            'com.digitalasset.canton.topology.admin.v30.SynchronizerPredecessor',
            [
                {
                    no: 1,
                    name: 'predecessor_physical_id',
                    kind: 'scalar',
                    T: 9 /*ScalarType.STRING*/,
                },
                {
                    no: 2,
                    name: 'upgrade_time',
                    kind: 'message',
                    T: () => Timestamp,
                },
                {
                    no: 3,
                    name: 'is_late_upgrade',
                    kind: 'scalar',
                    T: 8 /*ScalarType.BOOL*/,
                },
            ]
        )
    }
    create(
        value?: PartialMessage<SynchronizerPredecessor>
    ): SynchronizerPredecessor {
        const message = globalThis.Object.create(this.messagePrototype!)
        message.predecessorPhysicalId = ''
        message.isLateUpgrade = false
        if (value !== undefined)
            reflectionMergePartial<SynchronizerPredecessor>(
                this,
                message,
                value
            )
        return message
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: SynchronizerPredecessor
    ): SynchronizerPredecessor {
        let message = target ?? this.create(),
            end = reader.pos + length
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag()
            switch (fieldNo) {
                case /* string predecessor_physical_id */ 1:
                    message.predecessorPhysicalId = reader.string()
                    break
                case /* google.protobuf.Timestamp upgrade_time */ 2:
                    message.upgradeTime = Timestamp.internalBinaryRead(
                        reader,
                        reader.uint32(),
                        options,
                        message.upgradeTime
                    )
                    break
                case /* bool is_late_upgrade */ 3:
                    message.isLateUpgrade = reader.bool()
                    break
                default:
                    let u = options.readUnknownField
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        )
                    let d = reader.skip(wireType)
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(
                            this.typeName,
                            message,
                            fieldNo,
                            wireType,
                            d
                        )
            }
        }
        return message
    }
    internalBinaryWrite(
        message: SynchronizerPredecessor,
        writer: IBinaryWriter,
        options: BinaryWriteOptions
    ): IBinaryWriter {
        /* string predecessor_physical_id = 1; */
        if (message.predecessorPhysicalId !== '')
            writer
                .tag(1, WireType.LengthDelimited)
                .string(message.predecessorPhysicalId)
        /* google.protobuf.Timestamp upgrade_time = 2; */
        if (message.upgradeTime)
            Timestamp.internalBinaryWrite(
                message.upgradeTime,
                writer.tag(2, WireType.LengthDelimited).fork(),
                options
            ).join()
        /* bool is_late_upgrade = 3; */
        if (message.isLateUpgrade !== false)
            writer.tag(3, WireType.Varint).bool(message.isLateUpgrade)
        let u = options.writeUnknownFields
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(
                this.typeName,
                message,
                writer
            )
        return writer
    }
}
/**
 * @generated MessageType for protobuf message com.digitalasset.canton.topology.admin.v30.SynchronizerPredecessor
 */
export const SynchronizerPredecessor = new SynchronizerPredecessor$Type()
