// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "com/digitalasset/canton/topology/admin/v30/topology_manager_write_service.proto" (package "com.digitalasset.canton.topology.admin.v30", syntax proto3)
// tslint:disable
//
// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
import type { RpcTransport } from '@protobuf-ts/runtime-rpc'
import type { ServiceInfo } from '@protobuf-ts/runtime-rpc'
import { TopologyManagerWriteService } from './topology_manager_write_service.js'
import type { DropTemporaryTopologyStoreResponse } from './topology_manager_write_service.js'
import type { DropTemporaryTopologyStoreRequest } from './topology_manager_write_service.js'
import type { CreateTemporaryTopologyStoreResponse } from './topology_manager_write_service.js'
import type { CreateTemporaryTopologyStoreRequest } from './topology_manager_write_service.js'
import type { GenerateTransactionsResponse } from './topology_manager_write_service.js'
import type { GenerateTransactionsRequest } from './topology_manager_write_service.js'
import type { SignTransactionsResponse } from './topology_manager_write_service.js'
import type { SignTransactionsRequest } from './topology_manager_write_service.js'
import type { ImportTopologySnapshotV2Response } from './topology_manager_write_service.js'
import type { ImportTopologySnapshotV2Request } from './topology_manager_write_service.js'
import type { ImportTopologySnapshotResponse } from './topology_manager_write_service.js'
import type { ImportTopologySnapshotRequest } from './topology_manager_write_service.js'
import type { ClientStreamingCall } from '@protobuf-ts/runtime-rpc'
import type { AddTransactionsResponse } from './topology_manager_write_service.js'
import type { AddTransactionsRequest } from './topology_manager_write_service.js'
import { stackIntercept } from '@protobuf-ts/runtime-rpc'
import type { AuthorizeResponse } from './topology_manager_write_service.js'
import type { AuthorizeRequest } from './topology_manager_write_service.js'
import type { UnaryCall } from '@protobuf-ts/runtime-rpc'
import type { RpcOptions } from '@protobuf-ts/runtime-rpc'
/**
 * *
 * Write operations on the local topology manager.
 *
 * Participants, mediators, and sequencers run a local topology manager exposing the same write interface.
 *
 * @generated from protobuf service com.digitalasset.canton.topology.admin.v30.TopologyManagerWriteService
 */
export interface ITopologyManagerWriteServiceClient {
    /**
     * @generated from protobuf rpc: Authorize
     */
    authorize(
        input: AuthorizeRequest,
        options?: RpcOptions
    ): UnaryCall<AuthorizeRequest, AuthorizeResponse>
    /**
     * @generated from protobuf rpc: AddTransactions
     */
    addTransactions(
        input: AddTransactionsRequest,
        options?: RpcOptions
    ): UnaryCall<AddTransactionsRequest, AddTransactionsResponse>
    /**
     * Deprecated in favor of ImportTopologySnapshotV2
     *
     * @deprecated
     * @generated from protobuf rpc: ImportTopologySnapshot
     */
    importTopologySnapshot(
        options?: RpcOptions
    ): ClientStreamingCall<
        ImportTopologySnapshotRequest,
        ImportTopologySnapshotResponse
    >
    /**
     * @generated from protobuf rpc: ImportTopologySnapshotV2
     */
    importTopologySnapshotV2(
        options?: RpcOptions
    ): ClientStreamingCall<
        ImportTopologySnapshotV2Request,
        ImportTopologySnapshotV2Response
    >
    /**
     * @generated from protobuf rpc: SignTransactions
     */
    signTransactions(
        input: SignTransactionsRequest,
        options?: RpcOptions
    ): UnaryCall<SignTransactionsRequest, SignTransactionsResponse>
    /**
     * * RPC to generate topology transactions that can be signed
     *
     * @generated from protobuf rpc: GenerateTransactions
     */
    generateTransactions(
        input: GenerateTransactionsRequest,
        options?: RpcOptions
    ): UnaryCall<GenerateTransactionsRequest, GenerateTransactionsResponse>
    /**
     * * Creates a temporary topology store.
     * Trying to create a store with the same name results in an error.
     *
     * @generated from protobuf rpc: CreateTemporaryTopologyStore
     */
    createTemporaryTopologyStore(
        input: CreateTemporaryTopologyStoreRequest,
        options?: RpcOptions
    ): UnaryCall<
        CreateTemporaryTopologyStoreRequest,
        CreateTemporaryTopologyStoreResponse
    >
    /**
     * * Drops a temporary topology store.
     * Trying to drop a temporary store that does not exist results in an error.
     *
     * @generated from protobuf rpc: DropTemporaryTopologyStore
     */
    dropTemporaryTopologyStore(
        input: DropTemporaryTopologyStoreRequest,
        options?: RpcOptions
    ): UnaryCall<
        DropTemporaryTopologyStoreRequest,
        DropTemporaryTopologyStoreResponse
    >
}
/**
 * *
 * Write operations on the local topology manager.
 *
 * Participants, mediators, and sequencers run a local topology manager exposing the same write interface.
 *
 * @generated from protobuf service com.digitalasset.canton.topology.admin.v30.TopologyManagerWriteService
 */
export class TopologyManagerWriteServiceClient
    implements ITopologyManagerWriteServiceClient, ServiceInfo
{
    typeName = TopologyManagerWriteService.typeName
    methods = TopologyManagerWriteService.methods
    options = TopologyManagerWriteService.options
    constructor(private readonly _transport: RpcTransport) {}
    /**
     * @generated from protobuf rpc: Authorize
     */
    authorize(
        input: AuthorizeRequest,
        options?: RpcOptions
    ): UnaryCall<AuthorizeRequest, AuthorizeResponse> {
        const method = this.methods[0],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<AuthorizeRequest, AuthorizeResponse>(
            'unary',
            this._transport,
            method,
            opt,
            input
        )
    }
    /**
     * @generated from protobuf rpc: AddTransactions
     */
    addTransactions(
        input: AddTransactionsRequest,
        options?: RpcOptions
    ): UnaryCall<AddTransactionsRequest, AddTransactionsResponse> {
        const method = this.methods[1],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<AddTransactionsRequest, AddTransactionsResponse>(
            'unary',
            this._transport,
            method,
            opt,
            input
        )
    }
    /**
     * Deprecated in favor of ImportTopologySnapshotV2
     *
     * @deprecated
     * @generated from protobuf rpc: ImportTopologySnapshot
     */
    importTopologySnapshot(
        options?: RpcOptions
    ): ClientStreamingCall<
        ImportTopologySnapshotRequest,
        ImportTopologySnapshotResponse
    > {
        const method = this.methods[2],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ImportTopologySnapshotRequest,
            ImportTopologySnapshotResponse
        >('clientStreaming', this._transport, method, opt)
    }
    /**
     * @generated from protobuf rpc: ImportTopologySnapshotV2
     */
    importTopologySnapshotV2(
        options?: RpcOptions
    ): ClientStreamingCall<
        ImportTopologySnapshotV2Request,
        ImportTopologySnapshotV2Response
    > {
        const method = this.methods[3],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ImportTopologySnapshotV2Request,
            ImportTopologySnapshotV2Response
        >('clientStreaming', this._transport, method, opt)
    }
    /**
     * @generated from protobuf rpc: SignTransactions
     */
    signTransactions(
        input: SignTransactionsRequest,
        options?: RpcOptions
    ): UnaryCall<SignTransactionsRequest, SignTransactionsResponse> {
        const method = this.methods[4],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            SignTransactionsRequest,
            SignTransactionsResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * * RPC to generate topology transactions that can be signed
     *
     * @generated from protobuf rpc: GenerateTransactions
     */
    generateTransactions(
        input: GenerateTransactionsRequest,
        options?: RpcOptions
    ): UnaryCall<GenerateTransactionsRequest, GenerateTransactionsResponse> {
        const method = this.methods[5],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            GenerateTransactionsRequest,
            GenerateTransactionsResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * * Creates a temporary topology store.
     * Trying to create a store with the same name results in an error.
     *
     * @generated from protobuf rpc: CreateTemporaryTopologyStore
     */
    createTemporaryTopologyStore(
        input: CreateTemporaryTopologyStoreRequest,
        options?: RpcOptions
    ): UnaryCall<
        CreateTemporaryTopologyStoreRequest,
        CreateTemporaryTopologyStoreResponse
    > {
        const method = this.methods[6],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            CreateTemporaryTopologyStoreRequest,
            CreateTemporaryTopologyStoreResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * * Drops a temporary topology store.
     * Trying to drop a temporary store that does not exist results in an error.
     *
     * @generated from protobuf rpc: DropTemporaryTopologyStore
     */
    dropTemporaryTopologyStore(
        input: DropTemporaryTopologyStoreRequest,
        options?: RpcOptions
    ): UnaryCall<
        DropTemporaryTopologyStoreRequest,
        DropTemporaryTopologyStoreResponse
    > {
        const method = this.methods[7],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            DropTemporaryTopologyStoreRequest,
            DropTemporaryTopologyStoreResponse
        >('unary', this._transport, method, opt, input)
    }
}
