// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "com/digitalasset/canton/topology/admin/v30/topology_manager_read_service.proto" (package "com.digitalasset.canton.topology.admin.v30", syntax proto3)
// tslint:disable
//
// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
import type { RpcTransport } from '@protobuf-ts/runtime-rpc'
import type { ServiceInfo } from '@protobuf-ts/runtime-rpc'
import { TopologyManagerReadService } from './topology_manager_read_service.js'
import type { SequencerLsuStateResponse } from './topology_manager_read_service.js'
import type { SequencerLsuStateRequest } from './topology_manager_read_service.js'
import type { GenesisStateV2Response } from './topology_manager_read_service.js'
import type { GenesisStateV2Request } from './topology_manager_read_service.js'
import type { GenesisStateResponse } from './topology_manager_read_service.js'
import type { GenesisStateRequest } from './topology_manager_read_service.js'
import type { ExportTopologySnapshotV2Response } from './topology_manager_read_service.js'
import type { ExportTopologySnapshotV2Request } from './topology_manager_read_service.js'
import type { ExportTopologySnapshotResponse } from './topology_manager_read_service.js'
import type { ExportTopologySnapshotRequest } from './topology_manager_read_service.js'
import type { ServerStreamingCall } from '@protobuf-ts/runtime-rpc'
import type { ListAllV2Response } from './topology_manager_read_service.js'
import type { ListAllV2Request } from './topology_manager_read_service.js'
import type { ListAllResponse } from './topology_manager_read_service.js'
import type { ListAllRequest } from './topology_manager_read_service.js'
import type { ListAvailableStoresResponse } from './topology_manager_read_service.js'
import type { ListAvailableStoresRequest } from './topology_manager_read_service.js'
import type { ListLsuSequencerConnectionSuccessorResponse } from './topology_manager_read_service.js'
import type { ListLsuSequencerConnectionSuccessorRequest } from './topology_manager_read_service.js'
import type { ListLsuAnnouncementResponse } from './topology_manager_read_service.js'
import type { ListLsuAnnouncementRequest } from './topology_manager_read_service.js'
import type { ListSequencerSynchronizerStateResponse } from './topology_manager_read_service.js'
import type { ListSequencerSynchronizerStateRequest } from './topology_manager_read_service.js'
import type { ListMediatorSynchronizerStateResponse } from './topology_manager_read_service.js'
import type { ListMediatorSynchronizerStateRequest } from './topology_manager_read_service.js'
import type { ListSequencingParametersStateResponse } from './topology_manager_read_service.js'
import type { ListSequencingParametersStateRequest } from './topology_manager_read_service.js'
import type { ListSynchronizerParametersStateResponse } from './topology_manager_read_service.js'
import type { ListSynchronizerParametersStateRequest } from './topology_manager_read_service.js'
import type { ListPartyToParticipantResponse } from './topology_manager_read_service.js'
import type { ListPartyToParticipantRequest } from './topology_manager_read_service.js'
import type { ListVettedPackagesResponse } from './topology_manager_read_service.js'
import type { ListVettedPackagesRequest } from './topology_manager_read_service.js'
import type { ListPartyHostingLimitsResponse } from './topology_manager_read_service.js'
import type { ListPartyHostingLimitsRequest } from './topology_manager_read_service.js'
import type { ListParticipantSynchronizerPermissionResponse } from './topology_manager_read_service.js'
import type { ListParticipantSynchronizerPermissionRequest } from './topology_manager_read_service.js'
import type { ListSynchronizerTrustCertificateResponse } from './topology_manager_read_service.js'
import type { ListSynchronizerTrustCertificateRequest } from './topology_manager_read_service.js'
import type { ListPartyToKeyMappingResponse } from './topology_manager_read_service.js'
import type { ListPartyToKeyMappingRequest } from './topology_manager_read_service.js'
import type { ListOwnerToKeyMappingResponse } from './topology_manager_read_service.js'
import type { ListOwnerToKeyMappingRequest } from './topology_manager_read_service.js'
import type { ListDecentralizedNamespaceDefinitionResponse } from './topology_manager_read_service.js'
import type { ListDecentralizedNamespaceDefinitionRequest } from './topology_manager_read_service.js'
import { stackIntercept } from '@protobuf-ts/runtime-rpc'
import type { ListNamespaceDelegationResponse } from './topology_manager_read_service.js'
import type { ListNamespaceDelegationRequest } from './topology_manager_read_service.js'
import type { UnaryCall } from '@protobuf-ts/runtime-rpc'
import type { RpcOptions } from '@protobuf-ts/runtime-rpc'
/**
 * @generated from protobuf service com.digitalasset.canton.topology.admin.v30.TopologyManagerReadService
 */
export interface ITopologyManagerReadServiceClient {
    /**
     * @generated from protobuf rpc: ListNamespaceDelegation
     */
    listNamespaceDelegation(
        input: ListNamespaceDelegationRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListNamespaceDelegationRequest,
        ListNamespaceDelegationResponse
    >
    /**
     * @generated from protobuf rpc: ListDecentralizedNamespaceDefinition
     */
    listDecentralizedNamespaceDefinition(
        input: ListDecentralizedNamespaceDefinitionRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListDecentralizedNamespaceDefinitionRequest,
        ListDecentralizedNamespaceDefinitionResponse
    >
    /**
     * @generated from protobuf rpc: ListOwnerToKeyMapping
     */
    listOwnerToKeyMapping(
        input: ListOwnerToKeyMappingRequest,
        options?: RpcOptions
    ): UnaryCall<ListOwnerToKeyMappingRequest, ListOwnerToKeyMappingResponse>
    /**
     * Note that PartyToKeyMapping is deprecated in favor of PartyToParticipant
     *
     * @generated from protobuf rpc: ListPartyToKeyMapping
     */
    listPartyToKeyMapping(
        input: ListPartyToKeyMappingRequest,
        options?: RpcOptions
    ): UnaryCall<ListPartyToKeyMappingRequest, ListPartyToKeyMappingResponse>
    /**
     * @generated from protobuf rpc: ListSynchronizerTrustCertificate
     */
    listSynchronizerTrustCertificate(
        input: ListSynchronizerTrustCertificateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSynchronizerTrustCertificateRequest,
        ListSynchronizerTrustCertificateResponse
    >
    /**
     * @generated from protobuf rpc: ListParticipantSynchronizerPermission
     */
    listParticipantSynchronizerPermission(
        input: ListParticipantSynchronizerPermissionRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListParticipantSynchronizerPermissionRequest,
        ListParticipantSynchronizerPermissionResponse
    >
    /**
     * @generated from protobuf rpc: ListPartyHostingLimits
     */
    listPartyHostingLimits(
        input: ListPartyHostingLimitsRequest,
        options?: RpcOptions
    ): UnaryCall<ListPartyHostingLimitsRequest, ListPartyHostingLimitsResponse>
    /**
     * @generated from protobuf rpc: ListVettedPackages
     */
    listVettedPackages(
        input: ListVettedPackagesRequest,
        options?: RpcOptions
    ): UnaryCall<ListVettedPackagesRequest, ListVettedPackagesResponse>
    /**
     * @generated from protobuf rpc: ListPartyToParticipant
     */
    listPartyToParticipant(
        input: ListPartyToParticipantRequest,
        options?: RpcOptions
    ): UnaryCall<ListPartyToParticipantRequest, ListPartyToParticipantResponse>
    /**
     * @generated from protobuf rpc: ListSynchronizerParametersState
     */
    listSynchronizerParametersState(
        input: ListSynchronizerParametersStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSynchronizerParametersStateRequest,
        ListSynchronizerParametersStateResponse
    >
    /**
     * @generated from protobuf rpc: ListSequencingParametersState
     */
    listSequencingParametersState(
        input: ListSequencingParametersStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSequencingParametersStateRequest,
        ListSequencingParametersStateResponse
    >
    /**
     * @generated from protobuf rpc: ListMediatorSynchronizerState
     */
    listMediatorSynchronizerState(
        input: ListMediatorSynchronizerStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListMediatorSynchronizerStateRequest,
        ListMediatorSynchronizerStateResponse
    >
    /**
     * @generated from protobuf rpc: ListSequencerSynchronizerState
     */
    listSequencerSynchronizerState(
        input: ListSequencerSynchronizerStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSequencerSynchronizerStateRequest,
        ListSequencerSynchronizerStateResponse
    >
    /**
     * @generated from protobuf rpc: ListLsuAnnouncement
     */
    listLsuAnnouncement(
        input: ListLsuAnnouncementRequest,
        options?: RpcOptions
    ): UnaryCall<ListLsuAnnouncementRequest, ListLsuAnnouncementResponse>
    /**
     * @generated from protobuf rpc: ListLsuSequencerConnectionSuccessor
     */
    listLsuSequencerConnectionSuccessor(
        input: ListLsuSequencerConnectionSuccessorRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListLsuSequencerConnectionSuccessorRequest,
        ListLsuSequencerConnectionSuccessorResponse
    >
    /**
     * @generated from protobuf rpc: ListAvailableStores
     */
    listAvailableStores(
        input: ListAvailableStoresRequest,
        options?: RpcOptions
    ): UnaryCall<ListAvailableStoresRequest, ListAvailableStoresResponse>
    /**
     * @deprecated
     * @generated from protobuf rpc: ListAll
     */
    listAll(
        input: ListAllRequest,
        options?: RpcOptions
    ): UnaryCall<ListAllRequest, ListAllResponse>
    /**
     * @generated from protobuf rpc: ListAllV2
     */
    listAllV2(
        input: ListAllV2Request,
        options?: RpcOptions
    ): UnaryCall<ListAllV2Request, ListAllV2Response>
    /**
     * Deprecated in favor of ExportTopologySnapshotV2
     *
     * @deprecated
     * @generated from protobuf rpc: ExportTopologySnapshot
     */
    exportTopologySnapshot(
        input: ExportTopologySnapshotRequest,
        options?: RpcOptions
    ): ServerStreamingCall<
        ExportTopologySnapshotRequest,
        ExportTopologySnapshotResponse
    >
    /**
     * @generated from protobuf rpc: ExportTopologySnapshotV2
     */
    exportTopologySnapshotV2(
        input: ExportTopologySnapshotV2Request,
        options?: RpcOptions
    ): ServerStreamingCall<
        ExportTopologySnapshotV2Request,
        ExportTopologySnapshotV2Response
    >
    /**
     * Fetch the genesis topology state.
     * The returned bytestring can be used directly to initialize a sequencer.
     * Deprecated in favor of GenesisStateV2
     *
     * @deprecated
     * @generated from protobuf rpc: GenesisState
     */
    genesisState(
        input: GenesisStateRequest,
        options?: RpcOptions
    ): ServerStreamingCall<GenesisStateRequest, GenesisStateResponse>
    /**
     * @generated from protobuf rpc: GenesisStateV2
     */
    genesisStateV2(
        input: GenesisStateV2Request,
        options?: RpcOptions
    ): ServerStreamingCall<GenesisStateV2Request, GenesisStateV2Response>
    /**
     * Fetch the topology state
     * The returned bytestring can be used directly to initialize a successor sequencer
     *
     * @generated from protobuf rpc: SequencerLsuState
     */
    sequencerLsuState(
        input: SequencerLsuStateRequest,
        options?: RpcOptions
    ): ServerStreamingCall<SequencerLsuStateRequest, SequencerLsuStateResponse>
}
/**
 * @generated from protobuf service com.digitalasset.canton.topology.admin.v30.TopologyManagerReadService
 */
export class TopologyManagerReadServiceClient
    implements ITopologyManagerReadServiceClient, ServiceInfo
{
    typeName = TopologyManagerReadService.typeName
    methods = TopologyManagerReadService.methods
    options = TopologyManagerReadService.options
    constructor(private readonly _transport: RpcTransport) {}
    /**
     * @generated from protobuf rpc: ListNamespaceDelegation
     */
    listNamespaceDelegation(
        input: ListNamespaceDelegationRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListNamespaceDelegationRequest,
        ListNamespaceDelegationResponse
    > {
        const method = this.methods[0],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListNamespaceDelegationRequest,
            ListNamespaceDelegationResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListDecentralizedNamespaceDefinition
     */
    listDecentralizedNamespaceDefinition(
        input: ListDecentralizedNamespaceDefinitionRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListDecentralizedNamespaceDefinitionRequest,
        ListDecentralizedNamespaceDefinitionResponse
    > {
        const method = this.methods[1],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListDecentralizedNamespaceDefinitionRequest,
            ListDecentralizedNamespaceDefinitionResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListOwnerToKeyMapping
     */
    listOwnerToKeyMapping(
        input: ListOwnerToKeyMappingRequest,
        options?: RpcOptions
    ): UnaryCall<ListOwnerToKeyMappingRequest, ListOwnerToKeyMappingResponse> {
        const method = this.methods[2],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListOwnerToKeyMappingRequest,
            ListOwnerToKeyMappingResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * Note that PartyToKeyMapping is deprecated in favor of PartyToParticipant
     *
     * @generated from protobuf rpc: ListPartyToKeyMapping
     */
    listPartyToKeyMapping(
        input: ListPartyToKeyMappingRequest,
        options?: RpcOptions
    ): UnaryCall<ListPartyToKeyMappingRequest, ListPartyToKeyMappingResponse> {
        const method = this.methods[3],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListPartyToKeyMappingRequest,
            ListPartyToKeyMappingResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListSynchronizerTrustCertificate
     */
    listSynchronizerTrustCertificate(
        input: ListSynchronizerTrustCertificateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSynchronizerTrustCertificateRequest,
        ListSynchronizerTrustCertificateResponse
    > {
        const method = this.methods[4],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListSynchronizerTrustCertificateRequest,
            ListSynchronizerTrustCertificateResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListParticipantSynchronizerPermission
     */
    listParticipantSynchronizerPermission(
        input: ListParticipantSynchronizerPermissionRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListParticipantSynchronizerPermissionRequest,
        ListParticipantSynchronizerPermissionResponse
    > {
        const method = this.methods[5],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListParticipantSynchronizerPermissionRequest,
            ListParticipantSynchronizerPermissionResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListPartyHostingLimits
     */
    listPartyHostingLimits(
        input: ListPartyHostingLimitsRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListPartyHostingLimitsRequest,
        ListPartyHostingLimitsResponse
    > {
        const method = this.methods[6],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListPartyHostingLimitsRequest,
            ListPartyHostingLimitsResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListVettedPackages
     */
    listVettedPackages(
        input: ListVettedPackagesRequest,
        options?: RpcOptions
    ): UnaryCall<ListVettedPackagesRequest, ListVettedPackagesResponse> {
        const method = this.methods[7],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListVettedPackagesRequest,
            ListVettedPackagesResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListPartyToParticipant
     */
    listPartyToParticipant(
        input: ListPartyToParticipantRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListPartyToParticipantRequest,
        ListPartyToParticipantResponse
    > {
        const method = this.methods[8],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListPartyToParticipantRequest,
            ListPartyToParticipantResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListSynchronizerParametersState
     */
    listSynchronizerParametersState(
        input: ListSynchronizerParametersStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSynchronizerParametersStateRequest,
        ListSynchronizerParametersStateResponse
    > {
        const method = this.methods[9],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListSynchronizerParametersStateRequest,
            ListSynchronizerParametersStateResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListSequencingParametersState
     */
    listSequencingParametersState(
        input: ListSequencingParametersStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSequencingParametersStateRequest,
        ListSequencingParametersStateResponse
    > {
        const method = this.methods[10],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListSequencingParametersStateRequest,
            ListSequencingParametersStateResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListMediatorSynchronizerState
     */
    listMediatorSynchronizerState(
        input: ListMediatorSynchronizerStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListMediatorSynchronizerStateRequest,
        ListMediatorSynchronizerStateResponse
    > {
        const method = this.methods[11],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListMediatorSynchronizerStateRequest,
            ListMediatorSynchronizerStateResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListSequencerSynchronizerState
     */
    listSequencerSynchronizerState(
        input: ListSequencerSynchronizerStateRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListSequencerSynchronizerStateRequest,
        ListSequencerSynchronizerStateResponse
    > {
        const method = this.methods[12],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListSequencerSynchronizerStateRequest,
            ListSequencerSynchronizerStateResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListLsuAnnouncement
     */
    listLsuAnnouncement(
        input: ListLsuAnnouncementRequest,
        options?: RpcOptions
    ): UnaryCall<ListLsuAnnouncementRequest, ListLsuAnnouncementResponse> {
        const method = this.methods[13],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListLsuAnnouncementRequest,
            ListLsuAnnouncementResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListLsuSequencerConnectionSuccessor
     */
    listLsuSequencerConnectionSuccessor(
        input: ListLsuSequencerConnectionSuccessorRequest,
        options?: RpcOptions
    ): UnaryCall<
        ListLsuSequencerConnectionSuccessorRequest,
        ListLsuSequencerConnectionSuccessorResponse
    > {
        const method = this.methods[14],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListLsuSequencerConnectionSuccessorRequest,
            ListLsuSequencerConnectionSuccessorResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ListAvailableStores
     */
    listAvailableStores(
        input: ListAvailableStoresRequest,
        options?: RpcOptions
    ): UnaryCall<ListAvailableStoresRequest, ListAvailableStoresResponse> {
        const method = this.methods[15],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ListAvailableStoresRequest,
            ListAvailableStoresResponse
        >('unary', this._transport, method, opt, input)
    }
    /**
     * @deprecated
     * @generated from protobuf rpc: ListAll
     */
    listAll(
        input: ListAllRequest,
        options?: RpcOptions
    ): UnaryCall<ListAllRequest, ListAllResponse> {
        const method = this.methods[16],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<ListAllRequest, ListAllResponse>(
            'unary',
            this._transport,
            method,
            opt,
            input
        )
    }
    /**
     * @generated from protobuf rpc: ListAllV2
     */
    listAllV2(
        input: ListAllV2Request,
        options?: RpcOptions
    ): UnaryCall<ListAllV2Request, ListAllV2Response> {
        const method = this.methods[17],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<ListAllV2Request, ListAllV2Response>(
            'unary',
            this._transport,
            method,
            opt,
            input
        )
    }
    /**
     * Deprecated in favor of ExportTopologySnapshotV2
     *
     * @deprecated
     * @generated from protobuf rpc: ExportTopologySnapshot
     */
    exportTopologySnapshot(
        input: ExportTopologySnapshotRequest,
        options?: RpcOptions
    ): ServerStreamingCall<
        ExportTopologySnapshotRequest,
        ExportTopologySnapshotResponse
    > {
        const method = this.methods[18],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ExportTopologySnapshotRequest,
            ExportTopologySnapshotResponse
        >('serverStreaming', this._transport, method, opt, input)
    }
    /**
     * @generated from protobuf rpc: ExportTopologySnapshotV2
     */
    exportTopologySnapshotV2(
        input: ExportTopologySnapshotV2Request,
        options?: RpcOptions
    ): ServerStreamingCall<
        ExportTopologySnapshotV2Request,
        ExportTopologySnapshotV2Response
    > {
        const method = this.methods[19],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            ExportTopologySnapshotV2Request,
            ExportTopologySnapshotV2Response
        >('serverStreaming', this._transport, method, opt, input)
    }
    /**
     * Fetch the genesis topology state.
     * The returned bytestring can be used directly to initialize a sequencer.
     * Deprecated in favor of GenesisStateV2
     *
     * @deprecated
     * @generated from protobuf rpc: GenesisState
     */
    genesisState(
        input: GenesisStateRequest,
        options?: RpcOptions
    ): ServerStreamingCall<GenesisStateRequest, GenesisStateResponse> {
        const method = this.methods[20],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<GenesisStateRequest, GenesisStateResponse>(
            'serverStreaming',
            this._transport,
            method,
            opt,
            input
        )
    }
    /**
     * @generated from protobuf rpc: GenesisStateV2
     */
    genesisStateV2(
        input: GenesisStateV2Request,
        options?: RpcOptions
    ): ServerStreamingCall<GenesisStateV2Request, GenesisStateV2Response> {
        const method = this.methods[21],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<GenesisStateV2Request, GenesisStateV2Response>(
            'serverStreaming',
            this._transport,
            method,
            opt,
            input
        )
    }
    /**
     * Fetch the topology state
     * The returned bytestring can be used directly to initialize a successor sequencer
     *
     * @generated from protobuf rpc: SequencerLsuState
     */
    sequencerLsuState(
        input: SequencerLsuStateRequest,
        options?: RpcOptions
    ): ServerStreamingCall<
        SequencerLsuStateRequest,
        SequencerLsuStateResponse
    > {
        const method = this.methods[22],
            opt = this._transport.mergeOptions(options)
        return stackIntercept<
            SequencerLsuStateRequest,
            SequencerLsuStateResponse
        >('serverStreaming', this._transport, method, opt, input)
    }
}
